### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [LeoNatan/LNInterpolation#2]
I'd be cool to also add Cocoapods support. I done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by LeoNatan** [comment]
Hi,

I have a distinct dislike for CocoaPods, and do not wish to support it. I will soon add support for Carthage.

Thanks

**Comment by lfarah** [comment]
@LeoNatan I understand your dislike for CocoaPods and I've also tested Carthage in my own personal projects.
I would still love if LFInterpolation supported CocoaPods since a lot of people still use it and by supporting you're opening bigger horizons for your library.
Also by supporting CocoaPods, you're also supporting CocoaDocs, which let users check your documentation easily.
AwesomeiOS uses CocoaPods' quality index so we can better measure and rank libraries in our repository.

Again, I respect your opinion on CocoaPods, but I don't think your library support would cause any harm
